app:
    path: /{vueRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        vueRouting: "^(?!api).+"
    defaults:
        vueRouting: null

api:
    path: /api/summary
    controller: App\Controller\Api\ApiController::summary
    methods: [get]
